"""Error codes for structured error responses."""

# Validation errors
VALIDATION_ERROR_CODE = "VALIDATION_ERROR"

# Domain errors - Clash Detection
REQUEST_NOT_FOUND_CODE = "REQUEST_NOT_FOUND"
JOB_NOT_FOUND_CODE = "JOB_NOT_FOUND"
COMPLEXITY_LIMIT_EXCEEDED_CODE = "COMPLEXITY_LIMIT_EXCEEDED"
